---
title: "Moment Generating Functions"
format:
  revealjs:
    scrollable: true
    navigation-mode: vertical
    controls-layout: bottom-right
    controls-tutorial: true
    incremental: false 
    chalkboard:
      src: chalkboard.json
      storage: chalkboard_pres
      theme: whiteboard
      chalk-width: 4
editor: source
---

```{r}
#| include: false

knitr::opts_chunk$set(echo = T)

```

## Learning Outcomes

-   Moments

-   Moment Generating Functions

-   Properties

# Moments and Moment Generating Functions

## Expected Values

The *expected value* is the value we expect when we randomly sample from population that follows a specific distribution. The expected value of $Y$ is

$$
E(Y)=\sum_y yP(y)
$$

where $P(y)$ is the PMF of $Y$.

## Moments

Moments are numerical measures that describe the shape and characteristics of a random variable’s probability distribution.

::: fragment
The $k$th moment is described as

$$
E(X^k)
$$


:::

## Moment Generating Functions

The moment generating functions is used to obtain the $k$th moment. The mgf is defined as

$$
m(t) = E(e^{tX})
$$

The $k$th moment can be obtained by taking the $k$th derivative of the mgf, with respect to $t$, and setting $t$ equal to 0:

$$
E(X^k)=\frac{d^km(t)}{dt^k}\Bigg|_{c=0}
$$

# Binomial Distribution

## MGF

## $E(Y^2)$

# Poisson Distribution

## MGF

## $E(Y^2)$


# Expected Value Properties

## Properties

1.  $E(c)=c$, where $c$ is constant
2.  $E\{cg(Y)\}=cE\{g(Y)\}$
3.  $E\{g_1(Y)+\cdots+g_n(Y)\}=E\{g_1(Y)\}+\cdots+E\{g_n(Y)\}$