---
title: "Introduction to Probability"
format:
  revealjs:
    scrollable: true
    navigation-mode: vertical
    controls-layout: bottom-right
    controls-tutorial: true
    incremental: false 
    chalkboard:
      src: chalkboard.json
      storage: chalkboard_pres
      theme: whiteboard
      chalk-width: 4
editor: visual
---

## Learning Objectives

-   Define sample space and experiment

-   Define probabilities

-   Define random variable and distribution function

# Set Theory

## Sample Space

## Event

$S=\{a_1,a_2,a_3,a_4, a_5\}$

## Set Rules

$S=\{a_1,a_2,a_3,a_4, a_5\}$

## Set Rules

$S=\{a_1,a_2,a_3,a_4, a_5\}$

# Probability Functions

## Enumerating outcomes

$S=\{a_1,a_2,a_3,a_4, a_5\}$

## Probability Rules

## Probability Rules

# Random Variable

## Random Variable

## Probability Mass Function

## Cumulative Density Function

# Example

## Example

Suppose we want to understand the efficacy of a test for a certain disease. Consider the following table:

|             |     | Disease | Presence | Total |
|-------------|-----|---------|----------|-------|
|             |     | Yes     | No       |       |
| Test Result | Yes | 42      | 6        |       |
|             | No  | 17      | 35       |       |
|             |     |         |          | 100   |
|             |     |         |          |       |

## Example

::: nonincremental
-   Find the probability that an individual has a disease

-   Find the probability that an individual tests negative for a disease

-   Find the probability that and tests positive for a disease or they don't have the disease

-   Find the probability that the test gives an accurate result

-   Find the probability that the test gives and inaccurate result
:::