---
title: "Week 9"
date: 03-27-23
description: This week, we will discuss functions of random variables and sampling distributions.
editor: source
draft: true
editor_options: 
  chunk_output_type: console
---

## Learning Outcomes

### First Lecture

-   Functions of Random Variables

### Second Lecture

-   Sampling Distributions

## Important Concepts

### First Lecture

#### Functions of Random Variables

##### Method of Distribution Function

Let $Y=g(X)$ be a function of a Random variable $X$. The density function of $Y$ can be found with the following steps:

1.  Find the region of $Y$ in the $X$ space.
2.  Find the region of $Y\leq y$
3.  Find $F_Y(y)=P(Y\le y)$ by integrating over the region of $Y\le y$
4.  Find the density function $f_Y(y)=\frac{dF_Y(y)}{dy}$

##### Method of Transformations

Let $Y=g(X)$ be a function of a Random variable $X$, if $g(X)$ is either increasing or decreasing for all values of $X$ such that $f_X(x)>0$. Then the density function of $Y=g(X)$ is given as

$$
f_Y(y) = f_X\{g^{-1}(y)\}\left|\frac{dh^{-1}(y)}{dy}\right|
$$

##### Method of Moment Generating Functions

Let $Y=g(X)$ be a function of a Random variable $X$. Find the moment generating function $M_Y(t)$. Compare $M_Y(t)$ to known moment generating functions.

### Second Lecture

#### Sampling Distributions

##### Observing Random Variables

When collecting a sample of $n$, we tend to observe individual random variables: $\{X_1, X_2, \cdots,X_n\}$.

##### Sum of Random Variables

Let $X_i$, for $i=1, \cdots, n$, be identically and independently distributed (iid) normal distribution with mean $\mu$ and variance $\sigma^2$. Let $T=\sum_{i=1}^nX_i$ follow an normal distribution with mean $\mu$ and variance $n\sigma^2$.

#### Central Limit Theorem

Let $X_1, X_2, \ldots, X_n$ be identical and independent distributed random variables with $E(X_i)=\mu$ and $Var(X_i) = \sigma²$. We define

$$
Y_n = \sqrt n \left(\frac{\bar X-\mu}{\sigma}\right) \mathrm{ where }\ \bar X = \frac{1}{n}\sum^n_{i=1}X_i.
$$

Then, the distribution of the function $Y_n$ converges to a standard normal distribution function as $n\rightarrow \infty$.

#### Other Sampling Distributions

##### $\chi^2$-distribution

Let $Z_1, Z_2,\ldots,Z_n \overset{iid}{\sim}N(0,1)$,

$$
\sum_{i=1}^nZ_i^2\sim\chi^2_n.
$$

Let $X_1, X_2,\ldots,X_n \overset{iid}{\sim}N(\mu,\sigma^2)$, $S^2 = \frac{1}{n-1}\sum^n_{i=1}(X_i-\bar X)^2$, and $\bar X \perp S^2$; therefore:

$$
\frac{(n-1)S^2}{\sigma^2} \sim \chi^2_{n-1}.
$$

##### t-distribution

Let $Z\sim N(0,1)$, $W\sim \chi^2_\nu$, $Z\perp W$; therefore:

$$
T=\frac{Z}{\sqrt{W/\nu}} \sim t_\nu
$$

##### F-distribution

Let $W_1\sim\chi^2_{\nu_1}$ $W_2\sim\chi^2_{\nu_2}$, and $W_1\perp W_2$; therefore:

$$
F = \frac{W_1/\nu_1}{W_2/\nu_2}\sim F_{\nu_1,\nu_2}
$$

## Resources

### First Lecture

| Slides | Videos | Notes |
|--------------------|-------------------------|----------------------------|
| [Slides](https://m352.inqs.info/files/lecture_15.html) | [Video 001](https://youtu.be/ZHZa_Pju0vE) [Video 002](https://youtu.be/uikiB4WzjTE) | [Notes](https://m352.inqs.info/files/m002_15.pdf) |

### Second Lecture

| Slides | Videos | Notes |
|------------------------------|------------------------|------------------|
| [Slides](https://m352.inqs.info/files/lecture_16.html) | [Video 001](https://youtu.be/TqE8h4Skwp8) [Video 002](https://youtu.be/LbsRlp_thD8) | [Notes](https://m352.inqs.info/files/m002_16.pdf) |