---
title: "Week 14"
date: 03-27-23
description: This week, we will discuss functions of random variables and sampling distributions.
editor: source
draft: true
editor_options: 
  chunk_output_type: console
---

## Learning Outcomes

-   Introduction to Hypothesis Testing
-   Hypothesis Test Assumptions

## Resources

### First Lecture

| Slides | Videos | Notes |
|-------------|-----------------------------------------------|-------------|
| [Slides]() | [Video 001](https://youtu.be/q5yANeBYcfE) [Video 002](https://youtu.be/nZbrH0w-gZA) | [Notes 002]() |

### Second Lecture

| Slides | Videos | Notes |
|-------------------|------------------------|-----------------------------|
| [Slides](https://m352.inqs.info/files/lecture_25.html) | [Video 001](https://youtu.be/tH2xIxt_kPY) [Video 002](https://youtu.be/8VZMNJF1REE) | [Notes 001](https://m352.inqs.info/files/M_24_001.pdf) [Notes 002]() |

## Important Concepts

### Statistical Hypothesis Testing

A claim about the value of a certain parameter, a set of parameters, or a distribution.

#### Null Hypothesis $H_0$

The null hypothesis is the claim that is initially believed to be true. For the most part, it is always equal to the hypothesized value.

#### Alternative Hypothesis $H_a$

The alternative hypothesis contradicts the null hypothesis.

#### Examples of Null and Alternative Hypothesis Tests

| Null Hypothesis    | Alternative Hypothesis |
|--------------------|------------------------|
| $H_0: \mu=\mu_0$   | $H_a: \mu\ne\mu_0$     |
| $H_0: \mu\le\mu_0$ | $H_a: \mu>\mu_0$       |
| $H_0: \mu\ge\mu_0$ | $H_0: \mu<\mu_0$       |

#### Testing the Hypothesis

A hypothesis test is a statistical procedure to determine whether the null hypothesis is true or not. If we find that the null hypothesis is true, we claim: **Fail to reject the null hypothesis**. If we find the the null hypothesis to be false, we claim : **Reject the null hypothesis.**

To conduct a hypothesis test, we compute a test statistic based on the distribution of the null hypothesis. Then we determine if the test statistic is in the rejection region of the distribution of the null hypothesis. If it is in the rejection region, we reject the null hypothesis. Otherwise we fail to reject the null hypothesis.

The rejection region is determined by our $\alpha$ value. $\alpha$ determines the probability you are willing to be wrong if you reject the null hypothesis. This probability is something you want to set yourself at the beginning of a study. In general, the majority of researched set this to be $\alpha=0.05$.

#### One-Side vs Two-Side Hypothesis Tests

Notice how there are 3 types of null and alternative hypothesis, The first type of hypothesis ($H_a:\mu\ne\mu_0$) is considered a 2-sided hypothesis because the rejection region is located in 2 regions. The remaining two hypotheses are considered 1-sided because the rejection region is located on one side of the distribution.

| Null Hypothesis    | Alternative Hypothesis | Side    |
|--------------------|------------------------|---------|
| $H_0: \mu=\mu_0$   | $H_a: \mu\ne\mu_0$     | 2-sided |
| $H_0: \mu\le\mu_0$ | $H_a: \mu>\mu_0$       | 1-sided |
| $H_0: \mu\ge\mu_0$ | $H_0: \mu<\mu_0$       | 1-sided |

#### Hypothesis Test: Critical Value Approach

Depending on the type of test and alternative hypothesis, you may be asked to conduct the test using a critical value. This approach will require you to compute the test statistic (denoted as $T(x)$) and and compare it with a critical value(s). Depending on you alternative hypothesis and $\alpha$, you will reject the null hypothesis based on the following table:

| Alternative Hypothesis | Rejection Region | Critical value |
|-------------------|---------------------|--------------------------------|
| $\mu>\mu_0$ | $T(x)>CV$ | $P(X>CV)=\alpha$ |
| $\mu<\mu_0$ | $T(x)<CV$ | $P(X<CV)=\alpha$ |
| $\mu\ne\mu_0$ | $T(X)<CV_1$ or $T(X)>CV_2$ | $P(X<CV_1)=\alpha/2$ and $P(X>CV_2)=\alpha/2$ |

#### Hypothesis Test: P-value Approach

The p-value approach is one of the most common methods to report significant results. It is easier to interpret the p-value because it provides the probability of observing our test statistics, or something more extreme, given that the null hypothesis is true. Depending on the type of test, your p-value may be constructed as:

| Alternative Hypothesis | p-value                 |
|------------------------|-------------------------|
| $\mu>\mu_0$            | $P(X>T(x))=p$           |
| $\mu<\mu_0$            | $P(X<T(x))=p$           |
| $\mu\ne\mu_0$          | $2\times P(X>|T(X)|)=p$ |

If $p < \alpha$, then you reject $H_0$; otherwise, you will fail to reject $H_0$.

#### Hypothesis Test: Confidence Interval Approach

The confidence interval approach can evaluate a hypothesis test where the alternative hypothesis is $\mu\ne\mu_0$. For this approach you will construct a $(1-\alpha)100\%$ confidence interval as

$$
PE \pm CV *SE
$$

where PE is the point estimate, CV is the critical value based on $\alpha$ and SE is the standard error. This will result in a lower and upper bound denoted as: $(LB, UB)$. The confidence intervals provides a range values to capture the parameter $\mu$ such that if you repeat this process $n$ times, $(1-\alpha)100\%$ of $n$ will capture the true value of $\mu$. If $\mu_0 \in (LB,UB)$, then you fail to reject $H_0$. If $\mu_0\notin (LB,UB)$, then you reject $H_0$.

## More on Hypothesis Testing

| Playlist | Playlists | Notes |
|------------------|------------------------------------|------------------|
| Hypothesis Testing | [Videos](https://www.youtube.com/playlist?list=PLQmJJJJVDVnM9NFOQEzgyHjcl02LhFQYp) |  |
| Hypothesis Testing Examples | [Videos](https://www.youtube.com/playlist?list=PLQmJJJJVDVnPizJhMcCjGn0i2TzXMw3WA) |  |
| Hypothesis Test Assumptions | [Videos](https://www.youtube.com/playlist?list=PLQmJJJJVDVnPdIRn4NLNaynUzOvBOCAF6) |  |